### AVR executable Makefile stub for Posix

PROGRAMMER = -cusbtiny
#PROGRAMMER = -cstk500v1 -P/dev/tty.usbmodem34521
#NO_CORELIB = true
#OPTIMIZE = 3

F_CPU 	= 8000000L
MCU	= attiny85

LIBS 	+=
INC	+=

LFUSE	= 0xE2
HFUSE	= 0x5C
# WARNING - SETS THE RESET FUSE!!!

EFUSE 	= 0xFF

include ../base.mk

